### ISSUE TITLE
Improper linkifying

### ISSUE THREAD

**Issue by waldemarhorwat** [tc39/proposal-decimal#113]
Every instance of "A" is unintentionally turned into a link in the proposal, even if "A" is just the English indefinite article that often precedes a noun.

**Comment by jessealama** [comment]
Ack, you're right. I'll see what I can do to fix that. In the spec text, the link starts after the A/a/An/an but somehow ecmarkup took my `dfn` markup and did the wrong thing. I'm not sure if this is a bug with ecmarkup or I'm doing the wrong thing (the second is more likely).

**Comment by jessealama** [comment]
This has been taken care of now. I see no more manifestly bad linking in [the current spec](http://tc39.es/proposal-decimal/).
