### ISSUE TITLE
how about proposal-operator-overloading was withdrawn?

### ISSUE THREAD

**Issue by softboy99** [tc39/proposal-decimal#93]
[https://github.com/tc39/proposal-operator-overloading](url) was withdrawn, is there any influence with this proposal ?

**Comment by ljharb** [comment]
Yes, the same reason means that Decimal won't be able to be a primitive and thus have overloaded operators.

**Comment by munrocket** [comment]
Nice, after that polyfill will be easy to implement.

**Comment by ljharb** [comment]
It certainly makes it polyfillable (without that, it's not polyfillable at all) - but it unfortunately also makes for a much less compelling utility argument for advancing the proposal at all.

**Comment by jessealama** [comment]
Originally, the earlier iterations of this proposal did indeed aim to add decimals as a new primitive type, with overloading. But in the face of implementor response, we've scaled back the proposal to offer the functionality of decimal numbers. In our view, the need and demand for decimals among developers is great enough to overcome the bulkiness of a version of decimals without overloading.

**Comment by jessealama** [comment]
In other words, the withdrawal of the operator overloading proposal doesn't automatically kill the decimal proposal. They're related, but decimal has evolved to the point where it is no longer paired with operator overloading.
